# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies without triggering install scripts
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts

# Copy source and build tools
COPY . .

# Build the MCP server
RUN npm run build

# Default command to launch the MCP server via stdio transport
CMD ["node", "dist/cli.js"]
